comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
  branches: master          # branch names that can post comment
